model:
  base_learning_rate: 1.0e-06
  target: lidm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: [8, 128]
    channels: 8
    monitor: val/loss_simple_ema
    first_stage_key: image
    unet_config:
      target: lidm.modules.diffusion.dit_cspadfn_model.DiT
      params:
        input_size: [8, 128]
        patch_size: [1, 16]
        in_channels: 8
        out_channels: 8
        hidden_size: 1024
        depth: 24
        num_heads: 32
        num_head_channels: 32
        lib_name: lidm
    first_stage_config:
      target: lidm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 8
        n_embed: 16384
        lib_name: lidm
        use_mask: False  # False
        ckpt_path: logs/kitti/2024-11-27T15-12-21_autoencoder_nuscenes/checkpoints/epoch=000012.ckpt
        ddconfig:
          double_z: false
          z_channels: 8
          in_channels: 1
          out_ch: 1
          ch: 64
          ch_mult: [1,2,2,4]
          strides: [[1,2],[2,2],[2,2]]
          num_res_blocks: 2
          attn_levels: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    #max_epochs: 2
    wrap: true
    dataset:
      dataset_name: nuscenes
      size: [32, 1024]
      fov: [ 10,-30 ]
      depth_range: [ 1.0,45.0 ]
      depth_scale: 6.5
      log_scale: true
      x_range: [ -30.0, 30.0 ]
      y_range: [ -30.0, 30.0 ]
      z_range: [ -3.0, 6.0 ]
      resolution: 1
      num_channels: 1
      num_cats: 10
      num_views: 6
      num_sem_cats: 16
      filtered_map_cats: [ ]
    aug:
      flip: true
      rotate: false
      keypoint_drop: false
      keypoint_drop_range: [ 5,20 ]
      randaug: false
    train:
      target: lidm.data.nuscenes.NUSCENESImageTrain
      params:
        condition_key: image
    validation:
      target: lidm.data.nuscenes.NUSCENESImageValidation
      params:
        condition_key: image

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: true
